modLoader = "javafml"
loaderVersion = "[2,)"
license = "AGPL-3.0-only"
issueTrackerURL = "https://github.com/huanmeng-qwq/WindowFix/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "huanmeng_qwq"
description = '''${description}'''
